# Generated by Django 5.2.8 on 2025-11-26 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('estimated_hours', models.FloatField(help_text='Estimated hours to complete', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('importance', models.IntegerField(help_text='Importance rating from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of task IDs this task depends on')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority_score', 'due_date'],
            },
        ),
    ]
